// File generated by Antigravity (Enhanced with Web Support)
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu5A0WqsAGNY9kcCA36b9lgQTT_8VrjrQ',
    appId: '1:256566981785:web:c821f539f5c8bdb7f27408',
    messagingSenderId: '256566981785',
    projectId: 'ashall-1',
    authDomain: 'ashall-1.firebaseapp.com',
    storageBucket: 'ashall-1.firebasestorage.app',
    measurementId: 'G-0RG7HD4VXE',
    databaseURL: 'https://ashall-1-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVQmAVIKi--D7E_AEFhpubiLpufC3oyH8',
    appId: '1:284472595681:android:ff82435da8a025a45813a0',
    messagingSenderId: '284472595681',
    projectId: 'ashal1',
    storageBucket: 'ashal1.firebasestorage.app',
    databaseURL: 'https://ashal1-default-rtdb.firebaseio.com',
  );
}
